import * as React from 'react';
import Head from 'next/head';
import { getMDXComponent } from 'mdx-bundler/client';
import { getAllStaticPaths, getPageContents } from '../lib/getContents';
import { getSiteData } from '../lib/getSiteData';
import { SiteProvider } from '../providers/SiteProvider';

const RenderMDX = ({ mdx }) => {
  const MDXComponent = React.useMemo(() => getMDXComponent(mdx), [mdx]);
  return <MDXComponent {...mdx} />;
};

export default function Page({ params, site, mdx }) {
  return (
    <SiteProvider site={site} params={params}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RenderMDX mdx={mdx} />
      </main>
    </SiteProvider>
  );
}

export async function getStaticPaths() {
  const paths = await getAllStaticPaths();
  return {
    paths,
    fallback: false, // can also be true or 'blocking'
  };
}

export async function getStaticProps(context) {
  const { params } = context;
  const contents = await getPageContents(params.slug);
  const site = await getSiteData();

  return {
    // Passed to the page component as props
    props: {
      ...contents,
      site,
      params,
    },
  };
}
